# Generated by Django 2.1.2 on 2019-03-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20190323_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Team', models.CharField(max_length=50)),
                ('Away_Team', models.CharField(max_length=50)),
                ('Referee', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_goal', models.IntegerField()),
                ('Home_point', models.IntegerField()),
                ('Away_goal', models.IntegerField()),
                ('Away_point', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='scoreID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Score'),
        ),
    ]
