# Generated by Django 2.1.2 on 2019-03-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20190323_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='scoreID',
        ),
        migrations.AddField(
            model_name='score',
            name='FixtureID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='players.Fixture'),
            preserve_default=False,
        ),
    ]
