# Generated by Django 2.1.2 on 2019-03-25 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20190324_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pass', models.IntegerField()),
                ('Pass_Miss', models.IntegerField()),
                ('Point', models.IntegerField()),
                ('Point_Miss', models.IntegerField()),
                ('Goal', models.IntegerField()),
                ('Goal_Miss', models.IntegerField()),
                ('Turnover', models.IntegerField()),
                ('Lost_Possession', models.IntegerField()),
                ('Block', models.IntegerField()),
                ('Kickout_won', models.IntegerField()),
                ('Kickout_lost', models.IntegerField()),
                ('save', models.IntegerField()),
                ('Goal_conceded', models.IntegerField()),
                ('Yellow_card', models.IntegerField()),
                ('Red_card', models.IntegerField()),
                ('Black_card', models.IntegerField()),
                ('FixtureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Fixture')),
                ('PlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
