# Generated by Django 2.1.2 on 2019-03-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='FixtureID',
            new_name='Fixtures',
        ),
    ]
