# Generated by Django 2.1.2 on 2019-03-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20190327_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='Black_card',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='Block',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='Goal_conceded',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='Kickout_lost',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='Kickout_won',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='Lost_Possession',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='Red_card',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='Turnover',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='Yellow_card',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='save',
        ),
    ]
