# Generated by Django 2.1.2 on 2019-03-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_statistics_turnover'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='Block',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='Lost_Possession',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
