# Generated by Django 2.1.2 on 2019-03-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20190327_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='Block',
        ),
    ]
