# Generated by Django 2.1.2 on 2019-03-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_auto_20190327_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='Block',
            new_name='Lost_Possession',
        ),
    ]
