# Generated by Django 2.1.2 on 2019-03-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_auto_20190327_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='Lost_Possession',
            new_name='Dispossessed',
        ),
    ]
