# Generated by Django 2.1.2 on 2019-03-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_auto_20190327_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='Block',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
