# Generated by Django 2.1.2 on 2019-03-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_auto_20190327_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='Black_card',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='Goal_conceded',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='Red_card',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='Yellow_card',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='save',
        ),
    ]
