# Generated by Django 2.1.2 on 2019-03-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0021_auto_20190327_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='Black_card',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='Red_card',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='Yellow_card',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
